name: CI #name should be unique in the repository - specifies what it does

on: #when should this workflow run
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: #jobs are the individual tasks that make up the workflow
  test: #name of the job
    runs-on: ubuntu-latest #specifies the type of virtual machine to run the job on

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Adjust to your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build UnitTestDemo.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test UnitTestDemo.Tests/UnitTestDemo.Tests.csproj --no-build --configuration Release